---
title: "In Class Activity"
format: 
  html:
    code-tools: true
    toc: false
editor: source
---

## Overview & Objective

This activity will get quarto installed on your machine and producing documents.  At the end of this quick activity, you should be able to create and render relevant document types in the quarto system.


## The Activity

1. First, you must download the latest version of RStudio.  Go to [https://rstudio.org](https://rstudio.org) and download the latest build for your platform.  Follow the instructions relevant to your own operating system.

2. You should now download and install Quarto.  Go to [https://quarto.org](https://quarto.org) and download the latest version for your the operating system on your computer.

3. Open RStudio and select the `Terminal` tab (commonly found in the same pane as the one holding the R console) and type the following in to the terminal prompt.  This will install a basic pdf creation system on your computer so that you can render to PDF.

```
quarto install tool tinytex
```

Also, if you do not have chrome on your computer, have quarto install this as well.

```
quarto install tool chromium
```

4. Create and render the example quarto document (e.g., no need to change anything, just make a new one and hit render) to ensure you can create each type.


5. Commit your changes to this repository and push it back up to GitHub.  If you forget how to do this, consult the slides and narrative for the lecture on [GitHub](https://dyerlabteaching.github.io/Github/).